# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Python\_Project\quickey\ui\Forms\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1014, 690)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.actionTable = QtWidgets.QTableWidget(Form)
        self.actionTable.setObjectName("actionTable")
        self.actionTable.setColumnCount(0)
        self.actionTable.setRowCount(0)
        self.verticalLayout.addWidget(self.actionTable)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAdd = QtWidgets.QPushButton(self.widget_2)
        self.btnAdd.setMinimumSize(QtCore.QSize(40, 40))
        self.btnAdd.setMaximumSize(QtCore.QSize(40, 40))
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnDelete = QtWidgets.QPushButton(self.widget_2)
        self.btnDelete.setMinimumSize(QtCore.QSize(40, 40))
        self.btnDelete.setMaximumSize(QtCore.QSize(40, 40))
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.btnEdit = QtWidgets.QPushButton(self.widget_2)
        self.btnEdit.setMinimumSize(QtCore.QSize(40, 40))
        self.btnEdit.setMaximumSize(QtCore.QSize(40, 40))
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(0, 250))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "quickey"))
        self.btnAdd.setText(_translate("Form", "+"))
        self.btnDelete.setText(_translate("Form", "x"))
        self.btnEdit.setText(_translate("Form", "e"))
