# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Code\Python\_Project\quickey\ui\Forms\OpenFileWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenFileWidget(object):
    def setupUi(self, OpenFileWidget):
        OpenFileWidget.setObjectName("OpenFileWidget")
        OpenFileWidget.resize(625, 195)
        self.label = QtWidgets.QLabel(OpenFileWidget)
        self.label.setGeometry(QtCore.QRect(20, 80, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(OpenFileWidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 80, 201, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(OpenFileWidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 80, 71, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(OpenFileWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(OpenFileWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 40, 141, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.comboBox = QtWidgets.QComboBox(OpenFileWidget)
        self.comboBox.setGeometry(QtCore.QRect(90, 40, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(OpenFileWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 150, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(OpenFileWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 150, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(OpenFileWidget)
        QtCore.QMetaObject.connectSlotsByName(OpenFileWidget)

    def retranslateUi(self, OpenFileWidget):
        _translate = QtCore.QCoreApplication.translate
        OpenFileWidget.setWindowTitle(_translate("OpenFileWidget", "打开文件"))
        self.label.setText(_translate("OpenFileWidget", "程序路径"))
        self.pushButton.setText(_translate("OpenFileWidget", "选择..."))
        self.label_2.setText(_translate("OpenFileWidget", "触发方式"))
        self.comboBox.setItemText(0, _translate("OpenFileWidget", "快捷键组合"))
        self.comboBox.setItemText(1, _translate("OpenFileWidget", "双击某按键"))
        self.pushButton_2.setText(_translate("OpenFileWidget", "保存"))
        self.pushButton_3.setText(_translate("OpenFileWidget", "取消"))
